Repository frontendcafe/water-call-for-papers, pull requests merged in 2022-09, with the labels that each got.

#104 add notifications component
  stories/Alert/Alert.stories.tsx
  stories/Alert/Alert.tsx
Labels: frontend

#116 add service and endpoint to get all topics
  pages/api/topics/index.ts
  services/topic.ts
Labels: backend

#53 Crear componente Icons
  package-lock.json
  package.json
  pages/event/[eventId].tsx
  pages/event/list.tsx
  stories/Button/Button.stories.tsx
  stories/Icon/Icon.stories.tsx
  stories/Icon/Icon.tsx
  stories/Icons/Bookmark.tsx
  stories/Icons/DotsVertical.tsx
  stories/Icons/ErrorIcon.tsx
  stories/InputFile/InputFile.tsx
  stories/Modal/Modal.tsx
  stories/Spinner/Spinner.tsx
  stories/TextArea/TextArea.tsx
Labels: frontend, componente

#128 refactor: added firebase timestamp parsing
  lib/helpers.ts
Labels: backend

#129 refactor event dates
  services/events.ts
Labels: backend

#132 fix added missing properties
  mocks/events.ts
  mocks/talks.ts
  services/talks.ts
  types/talk-types.ts
Labels: backend

#75 Feat/crear componente tabs
  README.md
  stories/TabsGroup/Tab.tsx
  stories/TabsGroup/Tabs.stories.tsx
  stories/TabsGroup/TabsGroup.tsx
  stories/TabsGroup/TabsList.tsx
  stories/TabsGroup/TabsPanel.tsx
  stories/TabsGroup/TabsPanels.tsx
  stories/TabsGroup/types.d.ts
Labels: frontend, componente

#135 actualizar el componente Select
  stories/Icon/Icon.tsx
  stories/Select/Select.tsx
Labels: frontend, componente, refactor

#127 crear componentes cards
  lib/utils.ts
  package-lock.json
  package.json
  stories/Card/Card.stories.tsx
  stories/Card/Card.tsx
  stories/Card/CreateEventCard.tsx
  stories/MenuDropdown/MenuDropdown.tsx
  tailwind.config.js
Labels: frontend, componente

#94 35 crear un componente radio
  package-lock.json
  package.json
  pages/index.tsx
  stories/Input/InputText.tsx
  stories/Radio/Radio.stories.tsx
  stories/Radio/Radio.tsx
Labels: frontend

#107 74 crear el componente navigation drawer
  stories/Button/Button.tsx
  stories/SidebarDrawer/SidebarDrawer.stories.tsx
  stories/SidebarDrawer/SidebarDrawer.tsx
  stories/SidebarDrawer/StyledLink/StyledLink.tsx
  stories/SidebarDrawer/TextContainer.tsx
  stories/SidebarDrawer/useSidebarReducer.ts
  stories/Spinner/LogoCallForPapers.tsx
  styles/globals.css
Labels: frontend
