Repository frontendcafe/water-call-for-papers, pull requests merged in 2022-08, with the labels that each got.

#39 add recursion to get nested documents in database
  lib/firebase-config.ts
  lib/helpers.ts
Labels: backend

#40 13 crear un componente textarea
  stories/Icons/ErrorIcon.tsx
  stories/TextArea/TextArea.stories.tsx
  stories/TextArea/TextArea.tsx
Labels: frontend

#50 31 crear servicio para traer las postulaciones de un evento dado
  services/talks.ts
Labels: backend

#51 fix: changed type name for consistency
  types/talk-types.ts
Labels: backend

#34 Feat/crear componente tag
  stories/Tag/Tag.stories.tsx
  stories/Tag/Tag.tsx
  stories/TagList/TagList.stories.tsx
  stories/TagList/TagList.tsx
Labels: frontend

#38 Add/events
  lib/utils.ts
  package-lock.json
  package.json
  pages/api/candidate/index.ts
  pages/api/events/index.ts
  pages/api/hello.ts
  pages/api/organizers/index.ts
  services/events.ts
  services/organizers.ts
  types/events-types.ts
  types/others.ts
Labels: backend

#54 Nueva regla del linter para evitar type any
  .eslintrc
Labels: reestructurar

#36 14 investigar sobre el input tipo file
  .storybook/main.js
  package-lock.json
  package.json
  stories/InputFile/InputFile.stories.tsx
  stories/InputFile/InputFile.tsx
Labels: frontend

#56 29 crear servicio para añadir una postulación
  package-lock.json
  package.json
  services/talks.ts
  types/talk-types.ts
Labels: backend

#27 Feat/crear component input text
  stories/Input/Input.stories.tsx
  stories/Input/InputText.tsx
Labels: frontend

#82 add filter and sorting
  services/events.ts
  services/organizers.ts
Labels: backend

#52 33 crear servicio para traer una postulación
  services/talks.tsx
Labels: backend

#25 add button component
  pages/index.tsx
  stories/Button/Button.stories.tsx
  stories/Button/Button.tsx
  stories/Icons/Spinner.tsx
Labels: frontend

#80 #65 agregar manejo de respuestas
  lib/error-handling.ts
  lib/firebase-config.ts
  lib/helpers.ts
  pages/api/events/index.ts
  pages/api/hello.ts
  services/events.ts
  services/organizers.ts
  services/talks.ts
  services/talks.tsx
  types/others.ts
Labels: backend

#91 configurar un theme con Tailwind
  tailwind.config.js
Labels: frontend

#93 agregar endpoints para eventos #85
  pages/api/events/[id].ts
  pages/api/events/index.ts
  services/events.ts
  types/others.ts
Labels: backend

#111 Agregar endpoint para el agregado de un nuevo evento
  pages/api/events/index.ts
  services/events.ts
Labels: backend
